// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (user_id, action, entity, entity_id, metadata, ip)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAuditLogParams struct {
	UserID   pgtype.Int8
	Action   string
	Entity   string
	EntityID pgtype.Int8
	Metadata []byte
	Ip       string
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.UserID,
		arg.Action,
		arg.Entity,
		arg.EntityID,
		arg.Metadata,
		arg.Ip,
	)
	return err
}
