// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

type AuditLog struct {
	ID        int64
	UserID    pgtype.Int8
	Action    string
	Entity    string
	EntityID  pgtype.Int8
	Metadata  []byte
	Ip        string
	CreatedAt pgtype.Timestamptz
}

type Note struct {
	ID             int64
	UserID         int64
	Type           string
	Title          pgtype.Text
	Body           string
	Url            pgtype.Text
	Tags           []string
	AutoTags       []string
	Project        pgtype.Text
	Metadata       []byte
	FileKey        pgtype.Text
	FileName       pgtype.Text
	FileMime       pgtype.Text
	FileSize       pgtype.Int8
	ContentText    pgtype.Text
	Embedding      *pgvector_go.Vector
	ContentVersion int32
	IndexStatus    string
	IndexError     pgtype.Text
	Tsv            interface{}
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
	EmbeddingModel pgtype.Text
}

type Session struct {
	ID        int64
	UserID    int64
	TokenHash string
	UserAgent string
	Ip        string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID           int64
	Email        string
	Name         string
	AvatarUrl    pgtype.Text
	PasswordHash pgtype.Text
	GoogleSub    pgtype.Text
	Role         string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
