// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

const createNote = `-- name: CreateNote :one

INSERT INTO notes (user_id, type, title, body, url, tags, project, metadata,
                   file_key, file_name, file_mime, file_size)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8,
        $9, $10, $11, $12)
RETURNING id, user_id, type, title, body, url, tags, auto_tags, project, metadata,
          file_key, file_name, file_mime, file_size, index_status, content_version,
          created_at, updated_at
`

type CreateNoteParams struct {
	UserID   int64
	Type     string
	Title    pgtype.Text
	Body     string
	Url      pgtype.Text
	Tags     []string
	Project  pgtype.Text
	Metadata []byte
	FileKey  pgtype.Text
	FileName pgtype.Text
	FileMime pgtype.Text
	FileSize pgtype.Int8
}

type CreateNoteRow struct {
	ID             int64
	UserID         int64
	Type           string
	Title          pgtype.Text
	Body           string
	Url            pgtype.Text
	Tags           []string
	AutoTags       []string
	Project        pgtype.Text
	Metadata       []byte
	FileKey        pgtype.Text
	FileName       pgtype.Text
	FileMime       pgtype.Text
	FileSize       pgtype.Int8
	IndexStatus    string
	ContentVersion int32
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

// Semua query di sini di-scope user_id (ADR-007), kecuali ListPendingNotes
// yang hanya dipakai worker untuk safety net dan tidak mengembalikan isi note.
func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (CreateNoteRow, error) {
	row := q.db.QueryRow(ctx, createNote,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Url,
		arg.Tags,
		arg.Project,
		arg.Metadata,
		arg.FileKey,
		arg.FileName,
		arg.FileMime,
		arg.FileSize,
	)
	var i CreateNoteRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Url,
		&i.Tags,
		&i.AutoTags,
		&i.Project,
		&i.Metadata,
		&i.FileKey,
		&i.FileName,
		&i.FileMime,
		&i.FileSize,
		&i.IndexStatus,
		&i.ContentVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNote = `-- name: GetNote :one
SELECT id, user_id, type, title, body, url, tags, auto_tags, project, metadata,
       file_key, file_name, file_mime, file_size, index_status, content_version,
       created_at, updated_at
FROM notes
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetNoteParams struct {
	ID     int64
	UserID int64
}

type GetNoteRow struct {
	ID             int64
	UserID         int64
	Type           string
	Title          pgtype.Text
	Body           string
	Url            pgtype.Text
	Tags           []string
	AutoTags       []string
	Project        pgtype.Text
	Metadata       []byte
	FileKey        pgtype.Text
	FileName       pgtype.Text
	FileMime       pgtype.Text
	FileSize       pgtype.Int8
	IndexStatus    string
	ContentVersion int32
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetNote(ctx context.Context, arg GetNoteParams) (GetNoteRow, error) {
	row := q.db.QueryRow(ctx, getNote, arg.ID, arg.UserID)
	var i GetNoteRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Url,
		&i.Tags,
		&i.AutoTags,
		&i.Project,
		&i.Metadata,
		&i.FileKey,
		&i.FileName,
		&i.FileMime,
		&i.FileSize,
		&i.IndexStatus,
		&i.ContentVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNoteForIndex = `-- name: GetNoteForIndex :one
SELECT id, user_id, type, title, body, url, tags, project,
       file_key, file_name, file_mime, content_text, content_version
FROM notes
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetNoteForIndexParams struct {
	ID     int64
	UserID int64
}

type GetNoteForIndexRow struct {
	ID             int64
	UserID         int64
	Type           string
	Title          pgtype.Text
	Body           string
	Url            pgtype.Text
	Tags           []string
	Project        pgtype.Text
	FileKey        pgtype.Text
	FileName       pgtype.Text
	FileMime       pgtype.Text
	ContentText    pgtype.Text
	ContentVersion int32
}

func (q *Queries) GetNoteForIndex(ctx context.Context, arg GetNoteForIndexParams) (GetNoteForIndexRow, error) {
	row := q.db.QueryRow(ctx, getNoteForIndex, arg.ID, arg.UserID)
	var i GetNoteForIndexRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Url,
		&i.Tags,
		&i.Project,
		&i.FileKey,
		&i.FileName,
		&i.FileMime,
		&i.ContentText,
		&i.ContentVersion,
	)
	return i, err
}

const listNotes = `-- name: ListNotes :many
SELECT id, user_id, type, title, body, url, tags, auto_tags, project, metadata,
       file_key, file_name, file_mime, file_size, index_status, content_version,
       created_at, updated_at
FROM notes
WHERE user_id = $1
  AND deleted_at IS NULL
  AND ($2::text IS NULL OR type = $2::text)
  AND ($3::text IS NULL OR project = $3::text)
  AND ($4::text IS NULL
       OR $4::text = ANY(tags) OR $4::text = ANY(auto_tags))
  AND ($5::bigint IS NULL OR id < $5::bigint)
ORDER BY id DESC
LIMIT $6
`

type ListNotesParams struct {
	UserID   int64
	Type     pgtype.Text
	Project  pgtype.Text
	Tag      pgtype.Text
	BeforeID pgtype.Int8
	RowLimit int32
}

type ListNotesRow struct {
	ID             int64
	UserID         int64
	Type           string
	Title          pgtype.Text
	Body           string
	Url            pgtype.Text
	Tags           []string
	AutoTags       []string
	Project        pgtype.Text
	Metadata       []byte
	FileKey        pgtype.Text
	FileName       pgtype.Text
	FileMime       pgtype.Text
	FileSize       pgtype.Int8
	IndexStatus    string
	ContentVersion int32
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) ListNotes(ctx context.Context, arg ListNotesParams) ([]ListNotesRow, error) {
	rows, err := q.db.Query(ctx, listNotes,
		arg.UserID,
		arg.Type,
		arg.Project,
		arg.Tag,
		arg.BeforeID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotesRow
	for rows.Next() {
		var i ListNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Url,
			&i.Tags,
			&i.AutoTags,
			&i.Project,
			&i.Metadata,
			&i.FileKey,
			&i.FileName,
			&i.FileMime,
			&i.FileSize,
			&i.IndexStatus,
			&i.ContentVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingNotes = `-- name: ListPendingNotes :many
SELECT id, user_id, content_version
FROM notes
WHERE index_status = 'pending' AND deleted_at IS NULL
  AND updated_at < now() - make_interval(secs => $1::float8)
ORDER BY id
LIMIT $2
`

type ListPendingNotesParams struct {
	OlderThanSecs float64
	RowLimit      int32
}

type ListPendingNotesRow struct {
	ID             int64
	UserID         int64
	ContentVersion int32
}

func (q *Queries) ListPendingNotes(ctx context.Context, arg ListPendingNotesParams) ([]ListPendingNotesRow, error) {
	rows, err := q.db.Query(ctx, listPendingNotes, arg.OlderThanSecs, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingNotesRow
	for rows.Next() {
		var i ListPendingNotesRow
		if err := rows.Scan(&i.ID, &i.UserID, &i.ContentVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTypes = `-- name: ListTypes :many
SELECT type, count(*)::bigint AS total
FROM notes
WHERE user_id = $1 AND deleted_at IS NULL
GROUP BY type
ORDER BY total DESC, type
`

type ListTypesRow struct {
	Type  string
	Total int64
}

func (q *Queries) ListTypes(ctx context.Context, userID int64) ([]ListTypesRow, error) {
	rows, err := q.db.Query(ctx, listTypes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTypesRow
	for rows.Next() {
		var i ListTypesRow
		if err := rows.Scan(&i.Type, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNoteIndexFailed = `-- name: MarkNoteIndexFailed :exec
UPDATE notes
SET index_status = 'failed', index_error = $1
WHERE id = $2 AND user_id = $3
  AND content_version = $4
`

type MarkNoteIndexFailedParams struct {
	IndexError     pgtype.Text
	ID             int64
	UserID         int64
	ContentVersion int32
}

func (q *Queries) MarkNoteIndexFailed(ctx context.Context, arg MarkNoteIndexFailedParams) error {
	_, err := q.db.Exec(ctx, markNoteIndexFailed,
		arg.IndexError,
		arg.ID,
		arg.UserID,
		arg.ContentVersion,
	)
	return err
}

const markNoteIndexed = `-- name: MarkNoteIndexed :execrows
UPDATE notes
SET embedding = $1,
    embedding_model = $2,
    auto_tags = $3,
    index_status = 'done',
    index_error = NULL
WHERE id = $4 AND user_id = $5
  AND content_version = $6
`

type MarkNoteIndexedParams struct {
	Embedding      *pgvector_go.Vector
	EmbeddingModel pgtype.Text
	AutoTags       []string
	ID             int64
	UserID         int64
	ContentVersion int32
}

func (q *Queries) MarkNoteIndexed(ctx context.Context, arg MarkNoteIndexedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNoteIndexed,
		arg.Embedding,
		arg.EmbeddingModel,
		arg.AutoTags,
		arg.ID,
		arg.UserID,
		arg.ContentVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requeueNote = `-- name: RequeueNote :one
UPDATE notes
SET content_version = content_version + 1, index_status = 'pending', index_error = NULL
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, type, title, body, url, tags, auto_tags, project, metadata,
          file_key, file_name, file_mime, file_size, index_status, content_version,
          created_at, updated_at
`

type RequeueNoteParams struct {
	ID     int64
	UserID int64
}

type RequeueNoteRow struct {
	ID             int64
	UserID         int64
	Type           string
	Title          pgtype.Text
	Body           string
	Url            pgtype.Text
	Tags           []string
	AutoTags       []string
	Project        pgtype.Text
	Metadata       []byte
	FileKey        pgtype.Text
	FileName       pgtype.Text
	FileMime       pgtype.Text
	FileSize       pgtype.Int8
	IndexStatus    string
	ContentVersion int32
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) RequeueNote(ctx context.Context, arg RequeueNoteParams) (RequeueNoteRow, error) {
	row := q.db.QueryRow(ctx, requeueNote, arg.ID, arg.UserID)
	var i RequeueNoteRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Url,
		&i.Tags,
		&i.AutoTags,
		&i.Project,
		&i.Metadata,
		&i.FileKey,
		&i.FileName,
		&i.FileMime,
		&i.FileSize,
		&i.IndexStatus,
		&i.ContentVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const requeueStaleEmbeddings = `-- name: RequeueStaleEmbeddings :execrows
UPDATE notes
SET content_version = content_version + 1, index_status = 'pending', index_error = NULL
WHERE id IN (
  SELECT id FROM notes
  WHERE deleted_at IS NULL AND index_status <> 'pending'
    AND embedding_model IS DISTINCT FROM $1::text
  ORDER BY id
  LIMIT $2
)
`

type RequeueStaleEmbeddingsParams struct {
	Model    string
	RowLimit int32
}

// Tandai ulang note yang embedding-nya dibuat model lain (mis. setelah pindah Ollama -> OpenAI).
// Sistem-level (lintas user) seperti ListPendingNotes; tidak mengembalikan isi note.
func (q *Queries) RequeueStaleEmbeddings(ctx context.Context, arg RequeueStaleEmbeddingsParams) (int64, error) {
	result, err := q.db.Exec(ctx, requeueStaleEmbeddings, arg.Model, arg.RowLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveContentText = `-- name: SaveContentText :exec
UPDATE notes SET content_text = $1
WHERE id = $2 AND user_id = $3
`

type SaveContentTextParams struct {
	ContentText pgtype.Text
	ID          int64
	UserID      int64
}

func (q *Queries) SaveContentText(ctx context.Context, arg SaveContentTextParams) error {
	_, err := q.db.Exec(ctx, saveContentText, arg.ContentText, arg.ID, arg.UserID)
	return err
}

const softDeleteNote = `-- name: SoftDeleteNote :execrows
UPDATE notes SET deleted_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type SoftDeleteNoteParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) SoftDeleteNote(ctx context.Context, arg SoftDeleteNoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteNote, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes
SET type = $1,
    title = $2,
    body = $3,
    url = $4,
    tags = $5,
    project = $6,
    metadata = $7,
    content_version = CASE WHEN $8::bool THEN content_version + 1 ELSE content_version END,
    index_status = CASE WHEN $8::bool THEN 'pending' ELSE index_status END,
    updated_at = now()
WHERE id = $9 AND user_id = $10 AND deleted_at IS NULL
RETURNING id, user_id, type, title, body, url, tags, auto_tags, project, metadata,
          file_key, file_name, file_mime, file_size, index_status, content_version,
          created_at, updated_at
`

type UpdateNoteParams struct {
	Type           string
	Title          pgtype.Text
	Body           string
	Url            pgtype.Text
	Tags           []string
	Project        pgtype.Text
	Metadata       []byte
	ContentChanged bool
	ID             int64
	UserID         int64
}

type UpdateNoteRow struct {
	ID             int64
	UserID         int64
	Type           string
	Title          pgtype.Text
	Body           string
	Url            pgtype.Text
	Tags           []string
	AutoTags       []string
	Project        pgtype.Text
	Metadata       []byte
	FileKey        pgtype.Text
	FileName       pgtype.Text
	FileMime       pgtype.Text
	FileSize       pgtype.Int8
	IndexStatus    string
	ContentVersion int32
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (UpdateNoteRow, error) {
	row := q.db.QueryRow(ctx, updateNote,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Url,
		arg.Tags,
		arg.Project,
		arg.Metadata,
		arg.ContentChanged,
		arg.ID,
		arg.UserID,
	)
	var i UpdateNoteRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Url,
		&i.Tags,
		&i.AutoTags,
		&i.Project,
		&i.Metadata,
		&i.FileKey,
		&i.FileName,
		&i.FileMime,
		&i.FileSize,
		&i.IndexStatus,
		&i.ContentVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
