// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reminders.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueReminders = `-- name: ClaimDueReminders :many
UPDATE reminders SET status = 'sending', claimed_at = now(), updated_at = now()
WHERE id IN (
  SELECT id FROM reminders
  WHERE (status = 'pending' AND notify_at <= now())
     OR (status = 'sending' AND claimed_at < now() - interval '5 minutes')
  ORDER BY notify_at
  LIMIT $1
  FOR UPDATE SKIP LOCKED
)
RETURNING id, user_id, note_id, text, remind_at, repeat, lead_minutes, notify_at, notify_kind, status, attempts, claimed_at, last_sent_at, created_at, updated_at
`

// Query worker lintas user (pengecualian ADR-007): pengirim notifikasi memproses semua user,
// dan setiap baris membawa user_id-nya sendiri untuk menentukan penerima.
// Ambil reminder jatuh tempo untuk dikirim. SKIP LOCKED + status 'sending' mencegah kiriman dobel
// bila ada lebih dari satu worker; 'sending' yang tertahan >5 menit (worker crash) diambil ulang.
func (q *Queries) ClaimDueReminders(ctx context.Context, rowLimit int32) ([]Reminder, error) {
	rows, err := q.db.Query(ctx, claimDueReminders, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reminder
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NoteID,
			&i.Text,
			&i.RemindAt,
			&i.Repeat,
			&i.LeadMinutes,
			&i.NotifyAt,
			&i.NotifyKind,
			&i.Status,
			&i.Attempts,
			&i.ClaimedAt,
			&i.LastSentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createReminder = `-- name: CreateReminder :one
INSERT INTO reminders (user_id, note_id, text, remind_at, repeat, lead_minutes, notify_at, notify_kind)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8)
RETURNING id, user_id, note_id, text, remind_at, repeat, lead_minutes, notify_at, notify_kind, status, attempts, claimed_at, last_sent_at, created_at, updated_at
`

type CreateReminderParams struct {
	UserID      int64
	NoteID      pgtype.Int8
	Text        string
	RemindAt    pgtype.Timestamptz
	Repeat      string
	LeadMinutes []int32
	NotifyAt    pgtype.Timestamptz
	NotifyKind  string
}

func (q *Queries) CreateReminder(ctx context.Context, arg CreateReminderParams) (Reminder, error) {
	row := q.db.QueryRow(ctx, createReminder,
		arg.UserID,
		arg.NoteID,
		arg.Text,
		arg.RemindAt,
		arg.Repeat,
		arg.LeadMinutes,
		arg.NotifyAt,
		arg.NotifyKind,
	)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NoteID,
		&i.Text,
		&i.RemindAt,
		&i.Repeat,
		&i.LeadMinutes,
		&i.NotifyAt,
		&i.NotifyKind,
		&i.Status,
		&i.Attempts,
		&i.ClaimedAt,
		&i.LastSentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failReminderSend = `-- name: FailReminderSend :exec
UPDATE reminders
SET attempts = attempts + 1,
    status = CASE WHEN attempts + 1 >= $1::int THEN 'failed' ELSE 'pending' END,
    notify_at = now() + interval '1 minute', claimed_at = NULL, updated_at = now()
WHERE id = $2 AND status = 'sending'
`

type FailReminderSendParams struct {
	MaxAttempts int32
	ID          int64
}

// Query worker (pengecualian ADR-007): hanya baris yang sedang di-claim worker (status sending).
// Gagal kirim: coba lagi 1 menit kemudian; setelah max_attempts jadi failed.
func (q *Queries) FailReminderSend(ctx context.Context, arg FailReminderSendParams) error {
	_, err := q.db.Exec(ctx, failReminderSend, arg.MaxAttempts, arg.ID)
	return err
}

const finishReminderSend = `-- name: FinishReminderSend :exec
UPDATE reminders
SET status = $1, remind_at = $2, notify_at = $3,
    notify_kind = $4, attempts = 0, claimed_at = NULL,
    last_sent_at = now(), updated_at = now()
WHERE id = $5 AND status = 'sending'
`

type FinishReminderSendParams struct {
	Status     string
	RemindAt   pgtype.Timestamptz
	NotifyAt   pgtype.Timestamptz
	NotifyKind string
	ID         int64
}

// Query worker (pengecualian ADR-007): hanya baris yang sedang di-claim worker (status sending).
// Hasil kiriman: jadwal berikutnya (status pending) atau selesai (status sent).
func (q *Queries) FinishReminderSend(ctx context.Context, arg FinishReminderSendParams) error {
	_, err := q.db.Exec(ctx, finishReminderSend,
		arg.Status,
		arg.RemindAt,
		arg.NotifyAt,
		arg.NotifyKind,
		arg.ID,
	)
	return err
}

const getReminder = `-- name: GetReminder :one
SELECT id, user_id, note_id, text, remind_at, repeat, lead_minutes, notify_at, notify_kind, status, attempts, claimed_at, last_sent_at, created_at, updated_at FROM reminders WHERE id = $1 AND user_id = $2
`

type GetReminderParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetReminder(ctx context.Context, arg GetReminderParams) (Reminder, error) {
	row := q.db.QueryRow(ctx, getReminder, arg.ID, arg.UserID)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NoteID,
		&i.Text,
		&i.RemindAt,
		&i.Repeat,
		&i.LeadMinutes,
		&i.NotifyAt,
		&i.NotifyKind,
		&i.Status,
		&i.Attempts,
		&i.ClaimedAt,
		&i.LastSentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUpcomingReminders = `-- name: ListUpcomingReminders :many
SELECT id, user_id, note_id, text, remind_at, repeat, lead_minutes, notify_at, notify_kind, status, attempts, claimed_at, last_sent_at, created_at, updated_at FROM reminders
WHERE user_id = $1 AND status IN ('pending', 'sending')
ORDER BY notify_at
LIMIT $2
`

type ListUpcomingRemindersParams struct {
	UserID   int64
	RowLimit int32
}

// Reminder aktif (belum selesai/dibatalkan), urut notifikasi terdekat.
func (q *Queries) ListUpcomingReminders(ctx context.Context, arg ListUpcomingRemindersParams) ([]Reminder, error) {
	rows, err := q.db.Query(ctx, listUpcomingReminders, arg.UserID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reminder
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NoteID,
			&i.Text,
			&i.RemindAt,
			&i.Repeat,
			&i.LeadMinutes,
			&i.NotifyAt,
			&i.NotifyKind,
			&i.Status,
			&i.Attempts,
			&i.ClaimedAt,
			&i.LastSentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rescheduleReminder = `-- name: RescheduleReminder :one
UPDATE reminders
SET notify_at = $1, notify_kind = $2, status = 'pending',
    attempts = 0, updated_at = now()
WHERE id = $3 AND user_id = $4 AND status IN ('pending', 'sent', 'failed')
RETURNING id, user_id, note_id, text, remind_at, repeat, lead_minutes, notify_at, notify_kind, status, attempts, claimed_at, last_sent_at, created_at, updated_at
`

type RescheduleReminderParams struct {
	NotifyAt   pgtype.Timestamptz
	NotifyKind string
	ID         int64
	UserID     int64
}

// Tunda (snooze) atau aktifkan ulang: notifikasi berikutnya di notify_at.
func (q *Queries) RescheduleReminder(ctx context.Context, arg RescheduleReminderParams) (Reminder, error) {
	row := q.db.QueryRow(ctx, rescheduleReminder,
		arg.NotifyAt,
		arg.NotifyKind,
		arg.ID,
		arg.UserID,
	)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NoteID,
		&i.Text,
		&i.RemindAt,
		&i.Repeat,
		&i.LeadMinutes,
		&i.NotifyAt,
		&i.NotifyKind,
		&i.Status,
		&i.Attempts,
		&i.ClaimedAt,
		&i.LastSentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setReminderStatus = `-- name: SetReminderStatus :one
UPDATE reminders SET status = $1, updated_at = now()
WHERE id = $2 AND user_id = $3 AND status = ANY($4::text[])
RETURNING id, user_id, note_id, text, remind_at, repeat, lead_minutes, notify_at, notify_kind, status, attempts, claimed_at, last_sent_at, created_at, updated_at
`

type SetReminderStatusParams struct {
	Status     string
	ID         int64
	UserID     int64
	FromStatus []string
}

func (q *Queries) SetReminderStatus(ctx context.Context, arg SetReminderStatusParams) (Reminder, error) {
	row := q.db.QueryRow(ctx, setReminderStatus,
		arg.Status,
		arg.ID,
		arg.UserID,
		arg.FromStatus,
	)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NoteID,
		&i.Text,
		&i.RemindAt,
		&i.Repeat,
		&i.LeadMinutes,
		&i.NotifyAt,
		&i.NotifyKind,
		&i.Status,
		&i.Attempts,
		&i.ClaimedAt,
		&i.LastSentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
