// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

const hybridSearch = `-- name: HybridSearch :many
WITH q AS (
  SELECT websearch_to_tsquery('simple', $3::text) AS tsq
),
vec_candidates AS (
  SELECT n.id, n.embedding <=> $4::vector AS dist
  FROM notes n
  WHERE $4::vector IS NOT NULL
    AND n.user_id = $1 AND n.deleted_at IS NULL AND n.embedding IS NOT NULL
    AND n.embedding_model = $5::text
    -- Buang kandidat yang terlalu jauh maknanya, supaya hasil tidak berisik.
    AND n.embedding <=> $4::vector < $6::float8
    AND ($7::text IS NULL OR n.type = $7::text)
    AND ($8::text IS NULL OR n.project = $8::text)
    AND ($9::text IS NULL
         OR $9::text = ANY(n.tags) OR $9::text = ANY(n.auto_tags))
  ORDER BY dist
  LIMIT 50
),
vec AS (
  -- Hanya kandidat yang dekat dengan hasil terbaik (batas relatif).
  SELECT id, row_number() OVER (ORDER BY dist) AS rnk
  FROM vec_candidates
  WHERE dist <= (SELECT min(dist) FROM vec_candidates) + $10::float8
),
fts AS (
  SELECT n.id, row_number() OVER (ORDER BY ts_rank_cd(n.tsv, q.tsq) DESC) AS rnk
  FROM notes n, q
  WHERE n.user_id = $1 AND n.deleted_at IS NULL AND n.tsv @@ q.tsq
    AND ($7::text IS NULL OR n.type = $7::text)
    AND ($8::text IS NULL OR n.project = $8::text)
    AND ($9::text IS NULL
         OR $9::text = ANY(n.tags) OR $9::text = ANY(n.auto_tags))
  ORDER BY ts_rank_cd(n.tsv, q.tsq) DESC
  LIMIT 50
)
SELECT n.id, n.user_id, n.type, n.title, n.body, n.url, n.tags, n.auto_tags, n.project, n.metadata,
       n.file_key, n.file_name, n.file_mime, n.file_size, n.index_status, n.content_version,
       n.created_at, n.updated_at,
       (COALESCE(1.0 / (60 + vec.rnk), 0) + COALESCE(1.0 / (60 + fts.rnk), 0))::float8 AS score,
       CASE WHEN n.content_text IS NOT NULL
            THEN ts_headline('simple', n.content_text, q.tsq, 'MaxFragments=2, MaxWords=25, MinWords=8')
            ELSE '' END::text AS snippet
FROM vec
FULL OUTER JOIN fts ON vec.id = fts.id
JOIN notes n ON n.id = COALESCE(vec.id, fts.id)
CROSS JOIN q
WHERE n.user_id = $1
ORDER BY score DESC, n.id DESC
LIMIT $2
`

type HybridSearchParams struct {
	UserID         int64
	ResultLimit    int32
	Query          string
	QueryVec       *pgvector_go.Vector
	EmbeddingModel pgtype.Text
	MaxDistance    float64
	Type           pgtype.Text
	Project        pgtype.Text
	Tag            pgtype.Text
	RelativeMargin float64
}

type HybridSearchRow struct {
	ID             int64
	UserID         int64
	Type           string
	Title          pgtype.Text
	Body           string
	Url            pgtype.Text
	Tags           []string
	AutoTags       []string
	Project        pgtype.Text
	Metadata       []byte
	FileKey        pgtype.Text
	FileName       pgtype.Text
	FileMime       pgtype.Text
	FileSize       pgtype.Int8
	IndexStatus    string
	ContentVersion int32
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	Score          float64
	Snippet        string
}

// Vector similarity + full-text, digabung dengan Reciprocal Rank Fusion (ADR-002).
// query_vec NULL (provider embedding belum dikonfigurasi) => hanya full-text.
func (q *Queries) HybridSearch(ctx context.Context, arg HybridSearchParams) ([]HybridSearchRow, error) {
	rows, err := q.db.Query(ctx, hybridSearch,
		arg.UserID,
		arg.ResultLimit,
		arg.Query,
		arg.QueryVec,
		arg.EmbeddingModel,
		arg.MaxDistance,
		arg.Type,
		arg.Project,
		arg.Tag,
		arg.RelativeMargin,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HybridSearchRow
	for rows.Next() {
		var i HybridSearchRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Url,
			&i.Tags,
			&i.AutoTags,
			&i.Project,
			&i.Metadata,
			&i.FileKey,
			&i.FileName,
			&i.FileMime,
			&i.FileSize,
			&i.IndexStatus,
			&i.ContentVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Score,
			&i.Snippet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
