// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, password_hash, google_sub, avatar_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, name, avatar_url, password_hash, google_sub, role, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	Name         string
	PasswordHash pgtype.Text
	GoogleSub    pgtype.Text
	AvatarUrl    pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.GoogleSub,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.PasswordHash,
		&i.GoogleSub,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, avatar_url, password_hash, google_sub, role, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.PasswordHash,
		&i.GoogleSub,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByGoogleSub = `-- name: GetUserByGoogleSub :one
SELECT id, email, name, avatar_url, password_hash, google_sub, role, created_at, updated_at FROM users WHERE google_sub = $1
`

func (q *Queries) GetUserByGoogleSub(ctx context.Context, googleSub pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleSub, googleSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.PasswordHash,
		&i.GoogleSub,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, avatar_url, password_hash, google_sub, role, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.PasswordHash,
		&i.GoogleSub,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkGoogleAccount = `-- name: LinkGoogleAccount :one
UPDATE users
SET google_sub = $2,
    avatar_url = COALESCE(avatar_url, $3),
    name = CASE WHEN name = '' THEN $4 ELSE name END,
    updated_at = now()
WHERE id = $1
RETURNING id, email, name, avatar_url, password_hash, google_sub, role, created_at, updated_at
`

type LinkGoogleAccountParams struct {
	ID        int64
	GoogleSub pgtype.Text
	AvatarUrl pgtype.Text
	Name      string
}

func (q *Queries) LinkGoogleAccount(ctx context.Context, arg LinkGoogleAccountParams) (User, error) {
	row := q.db.QueryRow(ctx, linkGoogleAccount,
		arg.ID,
		arg.GoogleSub,
		arg.AvatarUrl,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.PasswordHash,
		&i.GoogleSub,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
